//! Gundam Halo — Tauri 2 application entry.
//!
//! Wraps the React frontend in a native Mac window with a persistent
//! menu bar tray icon. The tray icon is an **animated loop** (Unicorn
//! Gundam head in green Psycho-Frame awakening) — see
//! [`../../../docs/ARCHITECTURE.md`](../../../docs/ARCHITECTURE.md) §5.5.1
//! for design rationale.

mod commands; // Sprint 33 / Track 31-B — Personalised Fine-tune IPC commands.
mod recording; // Sprint 33 — recording pipeline stub (real impl deferred).
mod watchdog; // Sprint 43 — Self-Healing Backend (health probe + crash-loop guard).

use std::path::Path;
use std::process::Command;
use std::sync::atomic::{AtomicBool, AtomicU32, Ordering};
use std::sync::Arc;
use std::thread;
use std::time::Duration;

use include_dir::{include_dir, Dir};
use serde::Serialize;
use tauri::{
    image::Image as TauriImage,
    menu::{Menu, MenuItem, PredefinedMenuItem},
    tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent},
    Emitter, Manager,
};

// ============================================================================
// Animated tray icon
// ============================================================================

/// Embedded frame strip for the tray-icon animation. 88 frames at 15 FPS =
/// ~5.86 s seamless loop. Generated by `scripts/generate_tauri_icons.py` from
/// a 6 s video.
static ANIM_FRAMES: Dir = include_dir!("$CARGO_MANIFEST_DIR/icons/anim");

/// Animation cadence. Default 15 FPS is smooth enough for a small menu-bar
/// icon and cheap enough to run forever without thermal impact. Runtime-
/// tunable via the `set_animation_speed` Tauri command (see
/// `docs/ARCHITECTURE.md` §5.5.1). The bound is wide enough to cover both
/// battery-saver (8) and ultra-smooth (24) modes.
const DEFAULT_FPS: u32 = 15;
const MIN_FPS: u32 = 1;
const MAX_FPS: u32 = 60;

/// Process-wide tray animation FPS. Read by the animation thread on every
/// tick, so updates take effect on the next frame (no thread restart).
static ANIMATION_FPS: AtomicU32 = AtomicU32::new(DEFAULT_FPS);

/// Read the current FPS, clamped to the safe range. Defaults if the
/// stored value is somehow out of bounds (shouldn't happen — `set_*`
/// clamps on write — but defensive).
fn get_animation_fps() -> u32 {
    let raw = ANIMATION_FPS.load(Ordering::Relaxed);
    raw.clamp(MIN_FPS, MAX_FPS)
}

/// Sleep `1000 / fps` ms. Never sleeps zero.
fn frame_interval_ms() -> u64 {
    1000 / get_animation_fps() as u64
}

/// Decode every embedded PNG frame to a `TauriImage<'static>`.
/// The frames are sorted lexicographically by filename, so
/// `frame_001.png ... frame_088.png` play in order.
fn load_animation_frames() -> Result<Vec<TauriImage<'static>>, String> {
    let mut paths: Vec<_> = ANIM_FRAMES
        .files()
        .filter(|f| f.path().extension().and_then(|e| e.to_str()) == Some("png"))
        .collect();
    paths.sort_by_key(|f| f.path().to_path_buf());

    if paths.is_empty() {
        return Err("no animation frames found in icons/anim".into());
    }

    let mut frames = Vec::with_capacity(paths.len());
    for entry in paths {
        let img = image::load_from_memory(entry.contents())
            .map_err(|e| format!("decode {}: {e}", entry.path().display()))?;
        let (w, h) = image::GenericImageView::dimensions(&img);
        let rgba = img.to_rgba8().into_raw();
        // `Image::new` borrows from `rgba`; `to_owned()` flips it to
        // `Cow::Owned` so the image lives independently of `rgba`'s stack
        // frame.
        let owned = TauriImage::new(&rgba, w, h).to_owned();
        frames.push(owned);
    }
    Ok(frames)
}

/// Spawn a background thread that cycles through `frames`, calling
/// `tray.set_icon(...)` on each tick. Returns an `Arc<AtomicBool>` the
/// caller can flip to `true` to stop the thread (e.g. on app exit).
fn spawn_animation_thread(
    app: tauri::AppHandle,
    frames: Vec<TauriImage<'static>>,
) -> Arc<AtomicBool> {
    let stop = Arc::new(AtomicBool::new(false));
    let stop_clone = Arc::clone(&stop);

    thread::Builder::new()
        .name("halo-tray-anim".into())
        .spawn(move || {
            let mut index: usize = 0;
            while !stop_clone.load(Ordering::Relaxed) {
                // Tauri 2's `set_icon` is Send+Sync and uses internal locks,
                // so calling it from a non-main thread is safe on macOS and
                // Windows.
                if let Some(tray) = app.tray_by_id("main-tray") {
                    let _ = tray.set_icon(Some(frames[index].clone()));
                }
                index = (index + 1) % frames.len();
                // Read FPS each tick so `set_animation_speed` takes effect
                // immediately (no thread restart).
                thread::sleep(Duration::from_millis(frame_interval_ms()));
            }
        })
        .expect("failed to spawn tray animation thread");

    stop
}

// ============================================================================
// Window helpers
// ============================================================================

/// `true` when the app was launched with `--minimized` (i.e. should start
/// hidden in the tray). The autostart plugin is configured to pass this flag
/// so the agent comes back up silently after a reboot.
fn launched_minimized() -> bool {
    std::env::args().any(|a| a == "--minimized")
}

/// Show the main window and bring it to the foreground. No-op if already shown.
fn show_main_window(app: &tauri::AppHandle) {
    if let Some(window) = app.get_webview_window("main") {
        let _ = window.show();
        let _ = window.unminimize();
        let _ = window.set_focus();
    }
}

/// Hide the main window. The agent keeps running in the tray.
fn hide_main_window(app: &tauri::AppHandle) {
    if let Some(window) = app.get_webview_window("main") {
        let _ = window.hide();
    }
}

/// Toggle visibility. Used by tray left-click and macOS dock re-activation.
fn toggle_main_window(app: &tauri::AppHandle) {
    if let Some(window) = app.get_webview_window("main") {
        match window.is_visible() {
            Ok(true) => {
                let _ = window.hide();
            }
            _ => show_main_window(app),
        }
    }
}

#[tauri::command]
fn focus_main_window(app: tauri::AppHandle) {
    show_main_window(&app);
}

#[tauri::command]
fn hide_main_window_cmd(app: tauri::AppHandle) {
    hide_main_window(&app);
}

#[tauri::command]
fn new_chat(app: tauri::AppHandle) {
    // Bring the window forward and tell the frontend to start a new chat.
    show_main_window(&app);
    let _ = app.emit("halo://new-chat", ());
}

#[tauri::command]
fn open_settings(app: tauri::AppHandle) {
    show_main_window(&app);
    let _ = app.emit("halo://open-settings", ());
}

/// Set the tray animation FPS. Clamped to [`MIN_FPS`, `MAX_FPS`]. Takes
/// effect on the next animation frame (no thread restart). Returns the
/// effective value the runtime ended up using.
#[tauri::command]
fn set_animation_speed(fps: u32) -> u32 {
    let clamped = fps.clamp(MIN_FPS, MAX_FPS);
    ANIMATION_FPS.store(clamped, Ordering::Relaxed);
    clamped
}

/// Read the current tray animation FPS. Useful for a settings UI to
/// reflect the actual value after a clamp.
#[tauri::command]
fn get_animation_speed() -> u32 {
    get_animation_fps()
}

// ============================================================================
// Backend lifecycle
// ============================================================================

#[derive(Serialize)]
struct RestartResult {
    ok: bool,
    /// PID of the backend that was running before (or None if nothing
    /// was on the port).
    old_pid: Option<u32>,
    /// PID of the newly-spawned uvicorn process (or None on failure).
    new_pid: Option<u32>,
    /// Human-readable message — surfaced as a toast on the frontend.
    message: String,
}

/// Kill the uvicorn process bound to `port` and respawn it under
/// `uv` in the project backend. Used by the cockpit "Restart
/// backend" button on the backend-outdated banner.
///
/// Important: this command only kills the *uvicorn* on the given
/// port — it never touches the Tauri shell itself, so the dashboard
/// survives the restart. After the kill we sleep ~500ms before
/// spawning so the kernel can release the port.
#[tauri::command]
fn restart_backend(
    port: Option<u16>,
    repo_dir: Option<String>,
) -> RestartResult {
    let port = port.unwrap_or(8000);
    let repo_dir = repo_dir.unwrap_or_else(|| {
        // Default to the install.sh convention: $HOME/workspace/gundam-halo
        let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".into());
        format!("{}/workspace/gundam-halo", home)
    });

    // 1) Find the pid listening on `port` via lsof
    let old_pid = match Command::new("lsof")
        .args(["-ti", &format!("tcp:{}", port)])
        .output()
    {
        Ok(out) if out.status.success() => {
            let s = String::from_utf8_lossy(&out.stdout);
            s.trim().lines().next().and_then(|p| p.trim().parse::<u32>().ok())
        }
        Ok(_) => None, // lsof returned no rows — nothing on the port
        Err(e) => {
            return RestartResult {
                ok: false,
                old_pid: None,
                new_pid: None,
                message: format!("lsof not available: {}", e),
            };
        }
    };

    // 2) Kill the old process (if any)
    if let Some(pid) = old_pid {
        let _ = Command::new("kill").arg("-9").arg(pid.to_string()).output();
        // Wait for the port to actually free up
        std::thread::sleep(Duration::from_millis(500));
    }

    // 3) Spawn a fresh uvicorn in the background. Detach it from
    //    this process so it survives the Tauri shell.
    let backend_dir = format!("{}/backend", repo_dir);
    let spawn = Command::new("uv")
        .args([
            "run",
            "--project",
            &backend_dir,
            "uvicorn",
            "app.main:app",
            "--host",
            "0.0.0.0",
            "--port",
            &port.to_string(),
        ])
        .current_dir(&backend_dir)
        // Detach: stdout/stderr to /dev/null, don't keep a tty
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .spawn();

    match spawn {
        Ok(child) => {
            let new_pid = Some(child.id());
            // Intentionally drop `child` — Rust will not wait on
            // the killed `Command` because we don't keep the handle.
            std::mem::forget(child);
            RestartResult {
                ok: true,
                old_pid,
                new_pid,
                message: format!(
                    "Backend restarting (port {}). New pid: {}",
                    port,
                    new_pid.unwrap_or(0)
                ),
            }
        }
        Err(e) => RestartResult {
            ok: false,
            old_pid,
            new_pid: None,
            message: format!("Failed to spawn uvicorn: {}", e),
        },
    }
}

// ============================================================================
// App entry
// ============================================================================

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // Load animation frames at startup so the tray is animated as soon as
    // it appears. If loading fails, we fall back to the default window icon
    // and the tray stays static.
    let anim_frames = load_animation_frames().ok();

    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_global_shortcut::Builder::new().build())
        .plugin(tauri_plugin_autostart::init(
            tauri_plugin_autostart::MacosLauncher::LaunchAgent,
            Some(vec!["--minimized"]),
        ))
        .setup(move |app| {
            // ---- Tray menu ----
            // Order: Show → Hide → ─── → New Chat → Settings → ─── → Quit
            let show = MenuItem::with_id(app, "show", "Open Dashboard", true, None::<&str>)?;
            let hide = MenuItem::with_id(app, "hide", "Hide to Tray", true, None::<&str>)?;
            let sep1 = PredefinedMenuItem::separator(app)?;
            let new_chat =
                MenuItem::with_id(app, "new-chat", "New Chat", true, Some("CmdOrCtrl+N"))?;
            let settings =
                MenuItem::with_id(app, "settings", "Settings…", true, Some("CmdOrCtrl+,"))?;
            let sep2 = PredefinedMenuItem::separator(app)?;
            let quit =
                MenuItem::with_id(app, "quit", "Quit Gundam Halo", true, Some("CmdOrCtrl+Q"))?;

            let menu = Menu::with_items(
                app,
                &[&show, &hide, &sep1, &new_chat, &settings, &sep2, &quit],
            )?;

            // ---- Tray icon ----
            // Pick the first animation frame as the *initial* icon (so the
            // tray appears correctly before the animation thread kicks in).
            // The thread will overwrite it ~67 ms later.
            let initial_icon = match &anim_frames {
                Some(frames) if !frames.is_empty() => frames[0].clone(),
                _ => app
                    .default_window_icon()
                    .ok_or("no default window icon and no animation frames")?
                    .to_owned(),
            };

            let _tray = TrayIconBuilder::with_id("main-tray")
                .tooltip("Gundam Halo — personal AI agent")
                .icon(initial_icon)
                .menu(&menu)
                .show_menu_on_left_click(false)
                .on_menu_event(|app, event| match event.id.as_ref() {
                    "quit" => {
                        app.exit(0);
                    }
                    "show" => show_main_window(app),
                    "hide" => hide_main_window(app),
                    "new-chat" => {
                        show_main_window(app);
                        let _ = app.emit("halo://new-chat", ());
                    }
                    "settings" => {
                        show_main_window(app);
                        let _ = app.emit("halo://open-settings", ());
                    }
                    _ => {}
                })
                .on_tray_icon_event(|tray, event| {
                    if let TrayIconEvent::Click {
                        button: MouseButton::Left,
                        button_state: MouseButtonState::Up,
                        ..
                    } = event
                    {
                        toggle_main_window(tray.app_handle());
                    }
                })
                .build(app)?;

            // ---- Animation thread ----
            if let Some(frames) = anim_frames.clone() {
                let stop_flag = spawn_animation_thread(app.handle().clone(), frames);
                // Stash the stop flag on the app state so we could signal it
                // from elsewhere in the future (e.g. "pause animation when
                // battery < 20%"). For now the thread runs until process exit.
                app.manage(AnimationStop(stop_flag));
            }

            // ---- Sprint 43 watchdog thread ----
            // Pings /api/health every 60s; emits backend-unhealthy /
            // backend-recovered / backend-respawn-disabled Tauri events
            // when the state machine transitions. Complements launchd's
            // KeepAlive with a respawn-loop guard — see
            // docs/FEATURE-SPEC-SPRINT43-SELF-HEALING.md.
            let watchdog_stop = watchdog::start_watchdog(app.handle().clone());
            app.manage(WatchdogStop(watchdog_stop));

            // ---- Sprint 33 (Track 31-B) Personalised Fine-tune state ----
            // Register the in-memory `RecordingState` so the IPC
            // commands can `app.state::<recording::RecordingState>()`
            // when the real recording pipeline lands. Today the
            // state is default-constructed (all `None`); the
            // follow-up sprint will fill in the capture thread +
            // Whisper subprocess PID + manifest path + log tail.
            // See `frontend/src-tauri/src/recording.rs` for the
            // state shape + docs/FEATURE-SPEC-SPRINT26.md §4.1.
            app.manage(recording::RecordingState::default());

            // If launched with --minimized (e.g. autostart on login), keep
            // the window hidden so the agent lives in the tray.
            if launched_minimized() {
                hide_main_window(&app.handle());
            }

            Ok(())
        })
        // macOS: clicking the dock icon while the window is hidden should
        // bring it back, not just show an empty placeholder.
        .on_window_event(|window, event| {
            if let tauri::WindowEvent::CloseRequested { api, .. } = event {
                // Closing the window hides it to the tray instead of quitting.
                // Quit explicitly via the tray menu.
                let _ = window.hide();
                api.prevent_close();
            }
        })
        .invoke_handler(tauri::generate_handler![
            focus_main_window,
            hide_main_window_cmd,
            new_chat,
            open_settings,
            set_animation_speed,
            get_animation_speed,
            restart_backend,
            // Sprint 43 — Self-Healing Backend watchdog IPC commands.
            // The frontend calls these to:
            //   - `get_backend_health` → render the BackendHealthBanner
            //     initial state on cockpit mount
            //   - `install_launchd_supervisor` → one-click install
            //     when the supervisor plist isn't loaded
            //   - `clear_crash_log` → wipe the crash log via the
            //     backend's POST /api/system/clear-crash-log
            // See docs/FEATURE-SPEC-SPRINT43-SELF-HEALING.md.
            get_backend_health,
            install_launchd_supervisor,
            clear_crash_log,
            // Sprint 33 (Track 31-B) — Personalised Fine-tune
            // IPC commands. The 5 commands are stubs in this
            // sprint — the recording + training pipeline is
            // deferred per scope realism (~+770 LoC across 6
            // files including 2 NEW Rust files is too heavy
            // for a single sprint on top of the UI work).
            // Each command returns `phase: "stub"` from
            // `recording::stub_response` so the frontend can
            // show a clear "coming soon" toast — see
            // `frontend/src-tauri/src/{commands,recording}.rs`
            // for the contracts + docs/FEATURE-SPEC-SPRINT26.md
            // §4.1 for the full design.
            commands::start_record,
            commands::stop_record,
            commands::start_train,
            commands::get_train_progress,
            commands::activate_model,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

/// Wrapper so we can store the animation thread's stop flag in Tauri's
/// state container. Currently unused at runtime but reserved for future
/// hooks (battery saver, focus-state pause, etc.).
#[allow(dead_code)]
struct AnimationStop(Arc<AtomicBool>);

// ============================================================================
// `tray_by_id` import shim
// ============================================================================
// `Manager` provides `tray_by_id` in Tauri 2; this is just a no-op
// re-export note. The trait is already in scope via `use tauri::Manager`.
// ============================================================================

// keep `Path` import alive for future resource-lookup helpers
#[allow(dead_code)]
fn _path_anchor(_: &Path) {}

// ============================================================================
// Sprint 43 — Watchdog IPC commands
// ============================================================================

/// Stop-flag wrapper for the watchdog thread, stashed in Tauri state.
#[allow(dead_code)]
struct WatchdogStop(Arc<AtomicBool>);

#[derive(Serialize)]
struct BackendHealth {
    /// True if the launchd `com.gundam.halo` plist is loaded.
    installed: bool,
    /// PID of the supervised uvicorn, or None.
    pid: Option<u32>,
    /// Crash count in the last 60 min (from /api/system/health-detailed).
    crash_count_60m: u32,
    /// ISO 8601 timestamp of the most recent crash, or None.
    last_crash_at: Option<String>,
    /// ISO 8601 timestamp of the last watchdog poll (or app start).
    last_check_at: Option<String>,
    /// True if the backend reported respawn_disabled.
    respawn_disabled: bool,
}

/// Read the current backend health summary. The frontend calls this
/// on cockpit mount to render the BackendHealthBanner initial state
/// without waiting for the first watchdog poll.
#[tauri::command]
async fn get_backend_health() -> BackendHealth {
    use std::time::SystemTime;

    let body = watchdog::curl_get("http://localhost:8765/api/system/health-detailed");

    let (crash_count_60m, last_crash_at, respawn_disabled, installed, pid) =
        match body.as_deref() {
            Some(b) => {
                let v: serde_json::Value = serde_json::from_str(b).unwrap_or_default();
                let installed = v
                    .get("watchdog")
                    .and_then(|w| w.get("installed"))
                    .and_then(|x| x.as_bool())
                    .unwrap_or(false);
                let pid = v
                    .get("watchdog")
                    .and_then(|w| w.get("pid"))
                    .and_then(|x| x.as_u64())
                    .map(|p| p as u32);
                (
                    v.get("crash_count_60m").and_then(|x| x.as_u64()).unwrap_or(0) as u32,
                    v.get("last_crash_at").and_then(|x| x.as_str()).map(String::from),
                    v.get("respawn_disabled").and_then(|x| x.as_bool()).unwrap_or(false),
                    installed,
                    pid,
                )
            }
            None => (0, None, false, false, None),
        };

    // last_check_at = right now (best effort — the watchdog's
    // authoritative timestamp is in the events it emits).
    let last_check_at = SystemTime::now()
        .duration_since(SystemTime::UNIX_EPOCH)
        .ok()
        .map(|d| {
            chrono::DateTime::<chrono::Utc>::from_timestamp(d.as_secs() as i64, 0)
                .map(|dt| dt.to_rfc3339())
                .unwrap_or_default()
        });

    BackendHealth {
        installed,
        pid,
        crash_count_60m,
        last_crash_at,
        last_check_at,
        respawn_disabled,
    }
}

/// Install the launchd supervisor plist (`scripts/install-launchd.sh`).
///
/// This is the one-click "supervisor not installed" recovery path
/// from the BackendHealthBanner. The install script prompts for
/// sudo via the macOS GUI prompt (we don't capture stdin).
///
/// Returns the install output on success, or an error string on
/// failure (so the banner can display the reason).
#[tauri::command]
async fn install_launchd_supervisor(repo_dir: Option<String>) -> Result<String, String> {
    let repo_dir = repo_dir.unwrap_or_else(|| {
        let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".into());
        format!("{}/workspace/gundam-halo", home)
    });
    let script = format!("{}/scripts/install-launchd.sh", repo_dir);

    let output = Command::new("bash")
        .arg(&script)
        .output()
        .map_err(|e| format!("Failed to run {}: {}", script, e))?;

    if output.status.success() {
        Ok(String::from_utf8_lossy(&output.stdout).into_owned())
    } else {
        Err(String::from_utf8_lossy(&output.stderr).into_owned())
    }
}

/// Clear the backend crash log via POST /api/system/clear-crash-log.
///
/// Frontend wires this to the BackendHealthBanner "Clear crash log
/// & retry" button. Returns the cleared event count.
#[tauri::command]
async fn clear_crash_log() -> Result<u32, String> {
    let output = Command::new("curl")
        .args([
            "-sf",
            "-X",
            "POST",
            "--max-time",
            "5",
            "http://localhost:8765/api/system/clear-crash-log",
        ])
        .output()
        .map_err(|e| format!("curl failed: {}", e))?;

    if !output.status.success() {
        return Err(format!(
            "clear-crash-log returned non-2xx: {:?}",
            output.status.code()
        ));
    }

    let body = String::from_utf8_lossy(&output.stdout);
    let v: serde_json::Value = serde_json::from_str(&body)
        .map_err(|e| format!("invalid response JSON: {} (body: {})", e, body))?;
    Ok(v.get("cleared").and_then(|x| x.as_u64()).unwrap_or(0) as u32)
}
