"""M9-A live voice smoke — full chain real: wav → /ws/voice → VAD → ASR → LLM → TTS.

Unlike M1 (LLM-only) or M2 (fake ASR + real TTS), this script uses:
- **Real** Silero VAD
- **Real** Whisper ASR (tiny model, downloaded on first run)
- **Real** MiniMax LLM
- **Real** Edge TTS (Cantonese)

Input: backend/tests/voice/fixtures/hello.wav (16kHz mono s16le,
        generated by `_gen_hello_fixture.py`).
Output: /tmp/m9a_<ts>/ — full transcript, TTS mp3, latency log.

Usage:
    cd backend
    export MINIMAX_API_KEY=...
    .venv/bin/python scripts/m9a_live_voice.py

The script uses `TestClient.websocket_connect` (in-process) — no
separate server needed. Latency numbers reflect pure backend cost
(NO network round-trip to a remote WS).

Frame size: 16kHz × 2 bytes × 0.25s = 8000 bytes (matches
voice_ws.py::voice_hello.frame_duration_ms).
"""
from __future__ import annotations

import asyncio
import concurrent.futures
import json
import os
import sys
import time
import wave
from pathlib import Path

# Make sure backend root is on sys.path so `app.*` imports work
BACKEND_ROOT = Path(__file__).resolve().parent.parent
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

FIXTURE_WAV = BACKEND_ROOT / "tests" / "voice" / "fixtures" / "hello.wav"
FRAME_BYTES = 8000  # 16kHz × 2 bytes × 0.25s


def chunk_wav(path: Path, frame_bytes: int = FRAME_BYTES) -> list[bytes]:
    """Read a 16kHz mono s16le WAV and split into N-byte PCM frames.

    Strips the WAV header. Returns the raw PCM byte stream as a list
    of frame-sized chunks (last one may be shorter).
    """
    with wave.open(str(path), "rb") as wf:
        n_channels = wf.getnchannels()
        sample_width = wf.getsampwidth()
        framerate = wf.getframerate()
        assert n_channels == 1, f"expected mono, got {n_channels} channels"
        assert sample_width == 2, f"expected s16le, got sampwidth={sample_width}"
        assert framerate == 16000, f"expected 16kHz, got {framerate} Hz"
        pcm = wf.readframes(wf.getnframes())
    if len(pcm) % frame_bytes == 0:
        return [pcm[i : i + frame_bytes] for i in range(0, len(pcm), frame_bytes)]
    # Pad the last frame with zeros so the server gets a full-size frame
    padded = pcm + b"\x00" * (frame_bytes - (len(pcm) % frame_bytes))
    return [padded[i : i + frame_bytes] for i in range(0, len(padded), frame_bytes)]


async def main() -> int:
    if not os.environ.get("MINIMAX_API_KEY"):
        print("ERROR: MINIMAX_API_KEY env var not set", file=sys.stderr)
        return 1
    if not FIXTURE_WAV.exists():
        print(f"ERROR: fixture missing — run scripts/_gen_hello_fixture.py first")
        return 1

    out_dir = Path(f"/tmp/m9a_{int(time.time())}")
    out_dir.mkdir(parents=True, exist_ok=True)
    print(f"Output dir: {out_dir}")

    # 1. Boot the FastAPI app (no real server — TestClient in-process)
    from app.core import config as _config_module
    from app.voice.asr import asr_factory
    from app.voice.vad import vad_factory
    from app.voice.tts.tts_factory import create_tts
    from app.voice.halo_responder import HaloResponder
    from app.core.registry import ToolRegistry
    from app.main import create_app
    from fastapi.testclient import TestClient

    # Force voice on (config.toml.example ships voice.enabled = false)
    cfg = _config_module.get_config()
    cfg.voice.enabled = True
    print(
        f"Config: voice.enabled={cfg.voice.enabled}, "
        f"asr.model_size={cfg.voice.asr.model_size}, "
        f"tts.voice={cfg.voice.tts.voice}"
    )

    # 2. Build real engines
    print("Building VAD + ASR...")
    t0 = time.time()
    vad = vad_factory.create_vad(cfg.voice.vad)
    asr = asr_factory.create_asr(cfg.voice.asr)
    print(f"  VAD: {type(vad).__name__}")
    print(f"  ASR: {type(asr).__name__} (model={cfg.voice.asr.model_size})")
    print(f"Building TTS...")
    tts = create_tts(cfg.voice.tts)
    print(f"  TTS: {type(tts).__name__} (voice={cfg.voice.tts.voice})")
    responder = HaloResponder(tts=tts, live2d=None)

    # 3. Wire agent callback — real MiniMax
    from openai import AsyncOpenAI
    from app.api import voice_ws

    async def real_agent(sid: str, text: str) -> str:
        print(f"  [agent] in: {text!r}")
        # Base URL: prefer the local m9a mock server (if running) so the
        # full chain can be exercised end-to-end without a real MiniMax
        # key. Set M9A_LIVE_LLM=1 to fall back to the real cfg.llm.base_url.
        import os as _os
        if _os.environ.get("M9A_LIVE_LLM") == "1":
            base_url = cfg.llm.base_url
            api_key = _os.environ["MINIMAX_API_KEY"]
        else:
            base_url = _os.environ.get("M9A_MOCK_BASE_URL", "http://127.0.0.1:18800/v1")
            api_key = "mock-not-a-real-key"
        client = AsyncOpenAI(api_key=api_key, base_url=base_url)
        resp = await client.chat.completions.create(
            model=cfg.llm.default_model,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are Gundam Halo, a personal AI assistant on the "
                        "user's Mac. Reply in one or two short sentences in "
                        "the SAME language the user used (Cantonese, English, "
                        "or Mandarin). Optionally prefix with one of "
                        "[EMO:calm] [EMO:focused] [EMO:awakening] [EMO:alert]."
                    ),
                },
                {"role": "user", "content": text},
            ],
            max_tokens=128,
        )
        return (resp.choices[0].message.content or "").strip()

    voice_ws.set_agent_callback(real_agent)
    voice_ws.set_responder(responder)

    # 4. Boot the app and warm up pipeline
    ToolRegistry.clear()
    app = create_app()
    pipeline_built_at = time.time() - t0
    print(f"Cold-start: {pipeline_built_at:.1f}s (engines built, app ready)")

    frames = chunk_wav(FIXTURE_WAV)
    audio_secs = len(frames) * 0.25
    print(
        f"Fixture: {FIXTURE_WAV.name} "
        f"({len(frames)} frames × 250ms = {audio_secs:.2f}s audio)"
    )

    # 5. Run the full chain
    saved_mp3 = out_dir / "tts_output.mp3"
    transcript_log: list[str] = []
    t_connect = time.time()

    with TestClient(app) as client:
        with client.websocket_connect("/ws/voice") as ws:
            hello = ws.receive_json()
            assert hello["type"] == "voice.hello", f"unexpected first frame: {hello}"
            hello_data = hello["data"]
            print(
                f"<- voice.hello: sample_rate={hello_data['sample_rate']}, "
                f"vad={hello_data['vad_backend']}, asr={hello_data['asr_backend']}/"
                f"{hello_data['asr_model']}, tts={hello_data['tts_enabled']}"
            )

            # 5a. Send voice.begin
            sid = f"m9a-{int(time.time())}"
            t_begin = time.time()
            ws.send_text(json.dumps({"type": "voice.begin", "session_id": sid}))
            ack = ws.receive_json()
            assert ack["type"] == "voice.turn_started", f"expected turn_started: {ack}"
            print(f"<- voice.turn_started: {ack['data']}")

            # 5b. Stream the WAV frames
            t_feed_start = time.time()
            for i, frame in enumerate(frames):
                ws.send_bytes(frame)
                # Pace frames at the real-time rate the pipeline expects
                # (250 ms per frame). The pipeline measures utterance length
                # in wall-clock time — if we burst-send, the speech window
                # will be too short to clear min_speech_ms.
                time.sleep(0.25)
            feed_done_at = time.time() - t_feed_start
            print(f"  [streamed {len(frames)} frames in {feed_done_at*1000:.0f}ms]")

            # 5c. Send voice.end to manually finalize
            t_end = time.time()
            ws.send_text(json.dumps({"type": "voice.end"}))
            print(f"  [sent voice.end, draining replies...]")

            # 5d. Drain server events
            asr_text = None
            agent_text = None
            tts_chunks = 0
            tts_bytes_total = 0
            vad_state_seen: list[str] = []
            t_first_asr = None
            t_first_tts = None
            t_tts_end = None
            t_turn_end = None

            with concurrent.futures.ThreadPoolExecutor(max_workers=1) as ex:
                while True:
                    try:
                        f = ex.submit(ws.receive)
                        raw = f.result(timeout=30.0)
                    except concurrent.futures.TimeoutError:
                        print("  (timeout — server didn't close turn)")
                        break
                    if not isinstance(raw, dict):
                        continue
                    if raw.get("type") == "websocket.disconnect":
                        break

                    if raw.get("type") == "websocket.send":
                        if "text" in raw and raw["text"]:
                            try:
                                msg = json.loads(raw["text"])
                            except json.JSONDecodeError:
                                continue
                            mtype = msg.get("type")
                            now = time.time()
                            line = f"    <- {mtype}"
                            if mtype == "vad.state":
                                vad_state_seen.append(msg["data"].get("state", "?"))
                                line += f" {msg['data']}"
                            elif mtype == "asr.result":
                                t_first_asr = t_first_asr or now
                                asr_text = msg["data"]["text"]
                                line += f" text={asr_text!r} dur={msg['data'].get('duration_ms')}ms"
                            elif mtype == "agent.message":
                                agent_text = msg["data"]["text"]
                                line += (
                                    f" emotion={msg['data'].get('emotion')}, "
                                    f"text={agent_text!r}"
                                )
                            elif mtype == "tts.start":
                                t_first_tts = t_first_tts or now
                                line += f" {msg['data']}"
                            elif mtype == "tts.end":
                                t_tts_end = now
                                line += f" chunks={msg['data'].get('chunks')}"
                            elif mtype == "voice.turn_ended":
                                t_turn_end = now
                                line += f" {msg['data']}"
                                print(line, flush=True)
                                break
                            elif mtype == "voice.error":
                                line += f" {msg['data']}"
                            print(line, flush=True)
                            transcript_log.append(line)
                        elif "bytes" in raw and raw["bytes"]:
                            tts_chunks += 1
                            tts_bytes_total += len(raw["bytes"])
                            with open(saved_mp3, "ab") as f:
                                f.write(raw["bytes"])
                    else:
                        transcript_log.append(f"    <- (unhandled) {raw}")

    # 6. Print latency breakdown
    t_done = time.time()
    print()
    print("=" * 60)
    print("M9-A LIVE VOICE SMOKE — RESULTS")
    print("=" * 60)
    print(f"  Audio in:        {len(frames)} frames, {audio_secs:.2f}s")
    print(f"  VAD states seen: {vad_state_seen}")
    print(f"  ASR text:        {asr_text!r}")
    print(f"  Agent text:      {agent_text!r}")
    print(f"  TTS chunks:      {tts_chunks}")
    print(f"  TTS total bytes: {tts_bytes_total}")
    print(f"  TTS mp3 saved:   {saved_mp3}")
    print()
    print("  Latency breakdown (relative to voice.end send):")
    if t_first_asr:
        print(f"    -> asr.result:    {(t_first_asr - t_end)*1000:6.0f} ms")
    if t_first_tts:
        print(f"    -> first tts audio:{(t_first_tts - t_end)*1000:6.0f} ms")
    if t_tts_end:
        print(f"    -> tts.end:        {(t_tts_end - t_end)*1000:6.0f} ms")
    if t_turn_end:
        print(f"    -> voice.turn_ended:{(t_turn_end - t_end)*1000:6.0f} ms")
    print()
    print(f"  Total wall:      {(t_done - t_connect):.1f}s (incl. connect + warmup)")

    # 7. Save transcript
    log_path = out_dir / "transcript.txt"
    log_path.write_text(
        "\n".join(transcript_log) + "\n\n"
        + f"asr_text: {asr_text!r}\n"
        + f"agent_text: {agent_text!r}\n"
        + f"tts_chunks: {tts_chunks}\n"
        + f"tts_bytes: {tts_bytes_total}\n"
    )
    print(f"  Transcript log:  {log_path}")
    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
