"""SQLite index for sessions, messages, and threads.

Layered on top of the file-based persistence in
``app.projects.persistence``. The JSON files remain the source of
truth; this SQLite DB is a *queryable index* — fast lookups, filters,
counts, joins. It can always be regenerated by walking the JSON
files (see ``app.memory.lifecycle.rebuild_index``).

Threading
---------
This module opens **one** SQLite connection per ``SqliteIndex``
instance. We do *not* use a connection pool — the WAL mode
(``PRAGMA journal_mode=WAL``) plus ``check_same_thread=False``
makes the same connection safe to use from multiple threads in
our usage pattern (short-lived transactions, no long-held cursors).

If you need to share the index across many concurrent writers,
open one connection per thread via ``SqliteIndex.for_thread()``.

Schema
------
See ``M12 ticket`` for the full DDL. Schema version is
``SCHEMA_VERSION``; if the on-disk version is older we run a
rebuild.
"""
from __future__ import annotations

import json
import logging
import sqlite3
import threading
import time
from collections.abc import Iterator, Sequence
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Schema
# ---------------------------------------------------------------------------

SCHEMA_VERSION = 1

# Order matters: foreign keys depend on the parent table existing.
SCHEMA_DDL: tuple[str, ...] = (
    """
    CREATE TABLE IF NOT EXISTS schema_meta (
        key   TEXT PRIMARY KEY,
        value TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS sessions (
        session_id    TEXT PRIMARY KEY,
        project_name  TEXT NOT NULL,
        agent_type    TEXT NOT NULL,
        channel       TEXT,
        created_at    REAL NOT NULL,
        updated_at    REAL NOT NULL,
        message_count INTEGER NOT NULL DEFAULT 0
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_sessions_project ON sessions(project_name)",
    "CREATE INDEX IF NOT EXISTS idx_sessions_updated ON sessions(updated_at DESC)",
    """
    CREATE TABLE IF NOT EXISTS messages (
        message_id    INTEGER PRIMARY KEY AUTOINCREMENT,
        session_id    TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
        seq           INTEGER NOT NULL,
        role          TEXT NOT NULL,
        content       TEXT NOT NULL,
        tool_calls    TEXT,
        tool_call_id  TEXT,
        name          TEXT,
        created_at    REAL NOT NULL,
        UNIQUE (session_id, seq)
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_messages_session ON messages(session_id, seq)",
    "CREATE INDEX IF NOT EXISTS idx_messages_role ON messages(role)",
    """
    CREATE TABLE IF NOT EXISTS threads (
        thread_id     TEXT PRIMARY KEY,
        name          TEXT NOT NULL,
        project_name  TEXT,
        created_at    REAL NOT NULL,
        updated_at    REAL NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS session_thread (
        session_id  TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
        thread_id   TEXT NOT NULL REFERENCES threads(thread_id) ON DELETE CASCADE,
        PRIMARY KEY (session_id, thread_id)
    )
    """,
)


# ---------------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------------


@dataclass(slots=True, frozen=True)
class SessionRow:
    session_id: str
    project_name: str
    agent_type: str
    channel: str | None
    created_at: float
    updated_at: float
    message_count: int

    def to_dict(self) -> dict[str, Any]:
        return {
            "session_id": self.session_id,
            "project_name": self.project_name,
            "agent_type": self.agent_type,
            "channel": self.channel,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "message_count": self.message_count,
        }


@dataclass(slots=True, frozen=True)
class MessageRow:
    message_id: int
    session_id: str
    seq: int
    role: str
    content: str
    tool_calls: str | None  # JSON string
    tool_call_id: str | None
    name: str | None
    created_at: float

    def snippet(self, limit: int = 240) -> str:
        """Truncate content for previews (respects UTF-8 boundaries)."""
        if len(self.content) <= limit:
            return self.content
        # Cut on a character boundary
        return self.content[:limit].rsplit(" ", 1)[0] + "..."

    def to_dict(self) -> dict[str, Any]:
        return {
            "message_id": self.message_id,
            "session_id": self.session_id,
            "seq": self.seq,
            "role": self.role,
            "content": self.content,
            "tool_calls": json.loads(self.tool_calls) if self.tool_calls else None,
            "tool_call_id": self.tool_call_id,
            "name": self.name,
            "created_at": self.created_at,
        }


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _to_json(value: Any) -> str | None:
    """Serialize a value to JSON for storage, or None if value is None."""
    if value is None:
        return None
    return json.dumps(value, ensure_ascii=False, default=str)


# ---------------------------------------------------------------------------
# Index
# ---------------------------------------------------------------------------


class SqliteIndex:
    """SQLite index for sessions + messages.

    Lifecycle::

        idx = SqliteIndex(halo_home=Path("~/.gundam-halo"))
        idx.init()                       # create tables if missing
        idx.upsert_session(...)
        idx.upsert_messages(...)
        ... queries ...
        idx.close()
    """

    DEFAULT_FILENAME = "index.sqlite"

    def __init__(
        self,
        halo_home: Path,
        *,
        filename: str = DEFAULT_FILENAME,
        wal: bool = True,
    ) -> None:
        self._halo_home = halo_home
        self._path = halo_home / "memory" / filename
        self._path.parent.mkdir(parents=True, exist_ok=True)
        self._wal = wal
        self._local = threading.local()
        self._init_lock = threading.Lock()
        self._initialized = False

    # ------------------------------------------------------------------
    # Connection management
    # ------------------------------------------------------------------

    def _connect(self) -> sqlite3.Connection:
        conn = sqlite3.connect(
            str(self._path),
            check_same_thread=False,
            isolation_level=None,  # autocommit; we manage txns explicitly
        )
        conn.row_factory = sqlite3.Row
        # Foreign keys are off by default in SQLite — turn them on
        # so ON DELETE CASCADE actually works.
        conn.execute("PRAGMA foreign_keys = ON")
        if self._wal:
            # WAL gives better read concurrency; harmless if the
            # DB doesn't yet exist (the mode is set on first write).
            conn.execute("PRAGMA journal_mode = WAL")
        conn.execute("PRAGMA synchronous = NORMAL")
        return conn

    def conn(self) -> sqlite3.Connection:
        """Return a thread-local connection (lazy-created)."""
        c = getattr(self._local, "conn", None)
        if c is None:
            c = self._connect()
            self._local.conn = c
        return c

    @contextmanager
    def transaction(self) -> Iterator[sqlite3.Connection]:
        """Context manager wrapping BEGIN IMMEDIATE / COMMIT."""
        c = self.conn()
        c.execute("BEGIN IMMEDIATE")
        try:
            yield c
        except Exception:
            c.execute("ROLLBACK")
            raise
        else:
            c.execute("COMMIT")

    def close(self) -> None:
        c = getattr(self._local, "conn", None)
        if c is not None:
            try:
                c.close()
            except Exception:
                pass
            self._local.conn = None

    # ------------------------------------------------------------------
    # Schema bootstrap
    # ------------------------------------------------------------------

    def init(self) -> None:
        """Create tables if missing. Idempotent."""
        with self._init_lock:
            if self._initialized:
                return
            c = self.conn()
            for ddl in SCHEMA_DDL:
                c.execute(ddl)
            # Record schema version
            c.execute(
                "INSERT OR REPLACE INTO schema_meta (key, value) VALUES (?, ?)",
                ("schema_version", str(SCHEMA_VERSION)),
            )
            self._initialized = True
            logger.debug(f"Initialized SqliteIndex at {self._path}")

    def schema_version(self) -> int | None:
        """Return the on-disk schema version, or None if uninitialized."""
        if not self._path.exists():
            return None
        try:
            row = self.conn().execute(
                "SELECT value FROM schema_meta WHERE key='schema_version'"
            ).fetchone()
        except sqlite3.DatabaseError as e:
            logger.warning(f"Failed to read schema_meta: {e}")
            return None
        if row is None:
            return None
        try:
            return int(row["value"])
        except (ValueError, TypeError):
            return None

    def needs_rebuild(self) -> bool:
        """True if the on-disk version is older than SCHEMA_VERSION
        or the DB is missing entirely."""
        v = self.schema_version()
        return v != SCHEMA_VERSION

    def reset(self) -> None:
        """Drop all tables and recreate them. Used by rebuild_index()."""
        self.close()
        try:
            self._path.unlink()
        except FileNotFoundError:
            pass
        # Also drop the WAL sidecar files.
        for suffix in ("-wal", "-shm"):
            side = Path(str(self._path) + suffix)
            if side.exists():
                try:
                    side.unlink()
                except OSError:
                    pass
        self._initialized = False
        self.init()

    # ------------------------------------------------------------------
    # Session upsert
    # ------------------------------------------------------------------

    def upsert_session(
        self,
        *,
        session_id: str,
        project_name: str,
        agent_type: str,
        created_at: float,
        updated_at: float,
        channel: str | None = None,
        message_count: int = 0,
    ) -> None:
        """Insert or update a session row."""
        c = self.conn()
        c.execute(
            """
            INSERT INTO sessions
                (session_id, project_name, agent_type, channel,
                 created_at, updated_at, message_count)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(session_id) DO UPDATE SET
                project_name  = excluded.project_name,
                agent_type    = excluded.agent_type,
                channel       = excluded.channel,
                updated_at    = excluded.updated_at,
                message_count = excluded.message_count
            """,
            (
                session_id,
                project_name,
                agent_type,
                channel,
                created_at,
                updated_at,
                message_count,
            ),
        )

    def delete_session(self, session_id: str) -> bool:
        """Delete a session and its messages. Returns True if it existed."""
        c = self.conn()
        cur = c.execute(
            "DELETE FROM sessions WHERE session_id = ?", (session_id,)
        )
        return cur.rowcount > 0

    # ------------------------------------------------------------------
    # Message upsert
    # ------------------------------------------------------------------

    def upsert_messages(
        self,
        session_id: str,
        messages: Sequence[
            tuple[int, str, str, Any | None, str | None, str | None, float]
        ],
    ) -> None:
        """Bulk insert/replace messages for a session.

        ``messages`` is a sequence of
        ``(seq, role, content, tool_calls, tool_call_id, name, created_at)``
        tuples. Existing rows with the same ``(session_id, seq)`` are
        replaced (this matches our save semantics: the JSON file is
        the latest truth, so the index must mirror it).

        The whole batch runs in a single transaction.
        """
        if not messages:
            return
        c = self.conn()
        c.execute("BEGIN IMMEDIATE")
        try:
            # Wipe-and-rewrite is the simplest correct semantics for
            # a session: messages have a strict ordering, and the
            # latest save is always the truth. We could diff but the
            # JSON file is small enough that this is fine.
            c.execute(
                "DELETE FROM messages WHERE session_id = ?", (session_id,)
            )
            c.executemany(
                """
                INSERT INTO messages
                    (session_id, seq, role, content, tool_calls,
                     tool_call_id, name, created_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                """,
                [
                    (
                        session_id,
                        seq,
                        role,
                        content,
                        _to_json(tool_calls),
                        tool_call_id,
                        name,
                        created_at,
                    )
                    for (
                        seq,
                        role,
                        content,
                        tool_calls,
                        tool_call_id,
                        name,
                        created_at,
                    ) in messages
                ],
            )
            c.execute("COMMIT")
        except Exception:
            c.execute("ROLLBACK")
            raise

    # ------------------------------------------------------------------
    # Queries
    # ------------------------------------------------------------------

    def get_session(self, session_id: str) -> SessionRow | None:
        row = self.conn().execute(
            "SELECT * FROM sessions WHERE session_id = ?", (session_id,)
        ).fetchone()
        if row is None:
            return None
        return SessionRow(
            session_id=row["session_id"],
            project_name=row["project_name"],
            agent_type=row["agent_type"],
            channel=row["channel"],
            created_at=row["created_at"],
            updated_at=row["updated_at"],
            message_count=row["message_count"],
        )

    def list_sessions(
        self,
        *,
        project: str | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> list[SessionRow]:
        """List sessions, newest first."""
        c = self.conn()
        if project is not None:
            cur = c.execute(
                """
                SELECT * FROM sessions
                WHERE project_name = ?
                ORDER BY updated_at DESC
                LIMIT ? OFFSET ?
                """,
                (project, limit, offset),
            )
        else:
            cur = c.execute(
                """
                SELECT * FROM sessions
                ORDER BY updated_at DESC
                LIMIT ? OFFSET ?
                """,
                (limit, offset),
            )
        return [
            SessionRow(
                session_id=r["session_id"],
                project_name=r["project_name"],
                agent_type=r["agent_type"],
                channel=r["channel"],
                created_at=r["created_at"],
                updated_at=r["updated_at"],
                message_count=r["message_count"],
            )
            for r in cur.fetchall()
        ]

    def count_sessions(self, *, project: str | None = None) -> int:
        c = self.conn()
        if project is not None:
            row = c.execute(
                "SELECT COUNT(*) AS n FROM sessions WHERE project_name = ?",
                (project,),
            ).fetchone()
        else:
            row = c.execute("SELECT COUNT(*) AS n FROM sessions").fetchone()
        return int(row["n"]) if row else 0

    def get_messages(
        self,
        session_id: str,
        *,
        limit: int | None = None,
        offset: int = 0,
    ) -> list[MessageRow]:
        c = self.conn()
        if limit is None:
            cur = c.execute(
                "SELECT * FROM messages WHERE session_id = ? ORDER BY seq",
                (session_id,),
            )
        else:
            cur = c.execute(
                "SELECT * FROM messages WHERE session_id = ? "
                "ORDER BY seq LIMIT ? OFFSET ?",
                (session_id, limit, offset),
            )
        return [
            MessageRow(
                message_id=r["message_id"],
                session_id=r["session_id"],
                seq=r["seq"],
                role=r["role"],
                content=r["content"],
                tool_calls=r["tool_calls"],
                tool_call_id=r["tool_call_id"],
                name=r["name"],
                created_at=r["created_at"],
            )
            for r in cur.fetchall()
        ]

    def get_message(self, message_id: int) -> MessageRow | None:
        row = self.conn().execute(
            "SELECT * FROM messages WHERE message_id = ?", (message_id,)
        ).fetchone()
        if row is None:
            return None
        return MessageRow(
            message_id=row["message_id"],
            session_id=row["session_id"],
            seq=row["seq"],
            role=row["role"],
            content=row["content"],
            tool_calls=row["tool_calls"],
            tool_call_id=row["tool_call_id"],
            name=row["name"],
            created_at=row["created_at"],
        )

    def search_messages(
        self,
        query: str,
        *,
        project: str | None = None,
        limit: int = 50,
    ) -> list[MessageRow]:
        """LIKE search across message content.

        For semantic recall, use ``app.memory.vector_index`` —
        this is the cheap lexical fallback.
        """
        c = self.conn()
        like = f"%{query}%"
        if project is not None:
            cur = c.execute(
                """
                SELECT m.* FROM messages m
                JOIN sessions s ON s.session_id = m.session_id
                WHERE m.content LIKE ? AND s.project_name = ?
                ORDER BY m.created_at DESC
                LIMIT ?
                """,
                (like, project, limit),
            )
        else:
            cur = c.execute(
                """
                SELECT * FROM messages
                WHERE content LIKE ?
                ORDER BY created_at DESC
                LIMIT ?
                """,
                (like, limit),
            )
        return [
            MessageRow(
                message_id=r["message_id"],
                session_id=r["session_id"],
                seq=r["seq"],
                role=r["role"],
                content=r["content"],
                tool_calls=r["tool_calls"],
                tool_call_id=r["tool_call_id"],
                name=r["name"],
                created_at=r["created_at"],
            )
            for r in cur.fetchall()
        ]

    def iter_all_messages(
        self, *, batch_size: int = 500
    ) -> Iterator[MessageRow]:
        """Stream every message in the index — used by rebuild + bulk embed.

        Yields one row at a time. Uses server-side cursor via
        ``fetchmany`` to keep memory bounded.
        """
        c = self.conn()
        cur = c.execute(
            "SELECT * FROM messages ORDER BY session_id, seq"
        )
        while True:
            rows = cur.fetchmany(batch_size)
            if not rows:
                return
            for r in rows:
                yield MessageRow(
                    message_id=r["message_id"],
                    session_id=r["session_id"],
                    seq=r["seq"],
                    role=r["role"],
                    content=r["content"],
                    tool_calls=r["tool_calls"],
                    tool_call_id=r["tool_call_id"],
                    name=r["name"],
                    created_at=r["created_at"],
                )

    # ------------------------------------------------------------------
    # Threads (v0.2.0 — minimal: one project = one thread)
    # ------------------------------------------------------------------

    def ensure_project_thread(self, project_name: str) -> str:
        """Create a thread for a project if one doesn't exist.

        For v0.2.0 we map 1:1 (project → thread). The schema supports
        multi-session threads later.
        """
        c = self.conn()
        existing = c.execute(
            "SELECT thread_id FROM threads WHERE project_name = ? LIMIT 1",
            (project_name,),
        ).fetchone()
        if existing:
            return existing["thread_id"]
        thread_id = f"proj-{project_name}"
        now = time.time()
        try:
            c.execute(
                """
                INSERT INTO threads
                    (thread_id, name, project_name, created_at, updated_at)
                VALUES (?, ?, ?, ?, ?)
                """,
                (thread_id, project_name, project_name, now, now),
            )
        except sqlite3.IntegrityError:
            # Race: another thread/process created it. Re-fetch.
            row = c.execute(
                "SELECT thread_id FROM threads WHERE project_name = ? LIMIT 1",
                (project_name,),
            ).fetchone()
            if row is None:
                raise
            return row["thread_id"]
        return thread_id

    def attach_session_to_thread(
        self, session_id: str, thread_id: str
    ) -> None:
        c = self.conn()
        c.execute(
            "INSERT OR IGNORE INTO session_thread (session_id, thread_id) "
            "VALUES (?, ?)",
            (session_id, thread_id),
        )

    def list_threads(self) -> list[dict[str, Any]]:
        c = self.conn()
        cur = c.execute(
            """
            SELECT t.thread_id, t.name, t.project_name, t.created_at,
                   t.updated_at,
                   (SELECT COUNT(*) FROM session_thread st
                    WHERE st.thread_id = t.thread_id) AS session_count
            FROM threads t
            ORDER BY t.updated_at DESC
            """
        )
        return [dict(r) for r in cur.fetchall()]


# ---------------------------------------------------------------------------
# Module-level singleton
# ---------------------------------------------------------------------------


_index: SqliteIndex | None = None
_lock = threading.Lock()


def get_sqlite_index() -> SqliteIndex:
    global _index
    if _index is None:
        with _lock:
            if _index is None:
                from app.core.config import get_config

                cfg = get_config()
                idx = SqliteIndex(halo_home=cfg.home, wal=cfg.memory.sqlite_wal)
                idx.init()
                _index = idx
    return _index


def reset_sqlite_index() -> None:
    global _index
    if _index is not None:
        _index.close()
    _index = None


__all__ = [
    "SCHEMA_VERSION",
    "MessageRow",
    "SessionRow",
    "SqliteIndex",
    "get_sqlite_index",
    "reset_sqlite_index",
]
