/**
 * ImageSetAvatar → Theme-Keyed Image-Set Mode (Sprint 58+)
 *
 * Renders one of 9 pre-baked emotion PNGs (or an idle video loop)
 * generated by matrix image generation. Pairs alongside the
 * existing CSSAvatar (sprite sheet) as an alternate render mode:
 *
 *   - CSSAvatar: 88-frame sprite, continuous animation, emotion
 *     affects speed + halo hue. Use when the avatar should feel
 *     alive and breathing.
 *
 *   - ImageSetAvatar (this): 9 discrete emotion frames, instant
 *     swap on emotion change, optionally overlaid with a video
 *     loop when the avatar is idle. Use when the LLM needs a
 *     sharp, recognizable reaction (damage / joy / sad) without
 *     a 88-frame interpolation in between.
 *
 * ## Theme-keyed avatars (Sprint 58)
 *
 * The avatar is **theme-aware**: when the cockpit theme changes
 * (e.g. user picks SEED in the theme picker), the emotion PNGs
 * are loaded from `/avatars/emotions-<themeKey>/<emotion>.png`.
 * Each Gundam theme has its own character (Unicorn / Freedom /
 * Pilot / Setsuna / etc.) so the avatar visually matches the
 * selected universe.
 *
 * Themes WITHOUT a per-theme emotion set fall back to the
 * baseline `/avatars/emotions/` (the original 9 PNGs, NT-D
 * Unicorn). This is keyed by `THEMES_WITH_AVATAR_SET` below
 * — adding a new theme = add the directory + add to the set.
 *
 * Emotion names (v4 image set):
 *   idle, listening, thinking, speaking, warning,
 *   damage, joy, sad, confused
 *
 * The active emotion is read from the same `live2d.trigger` WS
 * stream CSSAvatar listens to, so either avatar can be mounted
 * without any upstream changes.
 */

import { useEffect, useMemo, useRef, useState } from "react";
import { subscribeToVoice } from "@/services/halo-live2d-bridge";
import { useSharedAmplitude } from "@/hooks/use-shared-amplitude";
import { useThemeStore } from "@/stores/theme";
import {
  type AvatarEmotion,
  buildAvatarImageMap,
} from "@/lib/avatar-paths";

interface ImageSetAvatarProps {
  /** Optional override; if absent, subscribes to live2d.trigger. */
  emotion?: string;
  /** Show scan line overlay (active/speaking). */
  active?: boolean;
  /** Render the idle video loop on top of the idle PNG. */
  enableVideoLoop?: boolean;
}

const IDLE_VIDEO = "/avatars/video/idle-loop.mp4";

/** Map upstream emotion names (calm/focused/awakening/...) to
 *  image-set names. The two systems are not 1:1; this is a
 *  best-effort passthrough. Unknown emotions fall through to idle.
 */
const UPSTREAM_TO_IMAGE: Record<string, AvatarEmotion> = {
  calm: "idle",
  focused: "thinking",
  awakening: "speaking",
  alert: "warning",
  damage: "damage",
  resolve: "joy",
  jubilant: "joy",
  stealth: "listening",
};

/** Set of valid v4 image-set emotion names — used to validate
 *  pass-through from upstream (live2d.trigger). Anything outside
 *  this set falls through to "idle". Kept local to avoid
 *  leaking the per-theme URL map into the dispatcher. */
const VALID_AVATAR_EMOTIONS: ReadonlySet<AvatarEmotion> = new Set<AvatarEmotion>([
  "idle",
  "listening",
  "thinking",
  "speaking",
  "warning",
  "damage",
  "joy",
  "sad",
  "confused",
]);

function resolveEmotion(input: string | undefined | null): AvatarEmotion {
  if (!input) return "idle";
  if (input in UPSTREAM_TO_IMAGE) return UPSTREAM_TO_IMAGE[input];
  if (VALID_AVATAR_EMOTIONS.has(input as AvatarEmotion)) {
    return input as AvatarEmotion;
  }
  return "idle";
}

export function ImageSetAvatar({
  emotion,
  active,
  enableVideoLoop = true,
}: ImageSetAvatarProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const amp = useSharedAmplitude();
  // Sprint 58: subscribe to the theme store so the avatar
  // swaps its emotion PNG set when the user picks a new theme.
  // useThemeStore.getState() is read on every render (cheap;
  // it's a plain object read), so theme changes propagate
  // without an explicit subscription.
  const theme = useThemeStore((s) => s.theme);
  const imageMap = useMemo(() => buildAvatarImageMap(theme), [theme]);
  const [resolved, setResolved] = useState<AvatarEmotion>(
    resolveEmotion(emotion),
  );
  const [preloaded, setPreloaded] = useState(false);

  // Subscribe to live2d.trigger WS for emotion updates
  useEffect(() => {
    const unsubscribe = subscribeToVoice("live2d.trigger", (event) => {
      const emo = (event as any).data?.emotion as string | undefined;
      setResolved(resolveEmotion(emo));
    });
    return unsubscribe;
  }, []);

  // Sync prop-driven emotion changes (covers manual override)
  useEffect(() => {
    setResolved(resolveEmotion(emotion));
  }, [emotion]);

  // Preload all 9 PNGs when the theme changes so emotion
  // switches stay instant. We depend on `imageMap` so the
  // preload re-runs when the user picks a new theme.
  useEffect(() => {
    let cancelled = false;
    Promise.all(
      Object.values(imageMap).map(
        (src) =>
          new Promise<void>((resolve) => {
            const img = new Image();
            img.onload = () => resolve();
            img.onerror = () => resolve(); // don't block on a broken image
            img.src = src;
          }),
      ),
    ).then(() => {
      if (!cancelled) setPreloaded(true);
    });
    return () => {
      cancelled = true;
    };
  }, [imageMap]);

  // Drive the idle video's playback rate by amplitude so the
  // breathing pace responds to voice activity. Loops via `loop`.
  useEffect(() => {
    if (!videoRef.current) return;
    const v = videoRef.current;
    v.playbackRate = 0.85 + amp * 0.6; // 0.85x silent → 1.45x talking
  }, [amp]);

  // Damage adds a shake to the container
  const shake = resolved === "damage" ? (Math.random() - 0.5) * 4 * amp : 0;
  const scale = 1.0 + amp * 0.08;

  const showVideo = enableVideoLoop && resolved === "idle";

  return (
    <div
      ref={containerRef}
      className={`imageset-avatar${active ? " imageset-avatar--active" : ""}`}
      aria-label={`Unicorn Avatar — ${resolved}`}
    >
      <div className="imageset-avatar__frame">
        <span className="imageset-avatar__bracket imageset-avatar__bracket--tl" />
        <span className="imageset-avatar__bracket imageset-avatar__bracket--tr" />
        <span className="imageset-avatar__bracket imageset-avatar__bracket--bl" />
        <span className="imageset-avatar__bracket imageset-avatar__bracket--br" />

        {active && <div className="imageset-avatar__scan" />}

        <div
          className="imageset-avatar__canvas"
          style={{
            transform: `scale(${scale.toFixed(3)}) translate(${shake.toFixed(2)}px, 0px)`,
            transition: "transform 60ms linear",
          }}
        >
          {/* Base PNG for current emotion (theme-keyed: NT-D
              defaults to /avatars/emotions/, SEED goes to
              /avatars/emotions-seed/, etc.). */}
          <img
            className="imageset-avatar__img"
            src={imageMap[resolved]}
            alt={resolved}
            draggable={false}
            style={{
              opacity: preloaded ? 1 : 0,
              transition: "opacity 200ms ease-out",
            }}
          />
          {/* Idle video loop, blended on top of the idle PNG */}
          {showVideo && (
            <video
              ref={videoRef}
              className="imageset-avatar__video"
              src={IDLE_VIDEO}
              autoPlay
              loop
              muted
              playsInline
            />
          )}
        </div>

        <div className="imageset-avatar__status">RX-0 · IMG</div>
      </div>

      <style>{`
        .imageset-avatar {
          width: 100%;
          height: 100%;
          position: relative;
          display: flex;
          align-items: center;
          justify-content: center;
        }
        .imageset-avatar__frame {
          position: relative;
          width: 100%;
          height: 100%;
          background: #0a0a12;
          overflow: hidden;
          border: 1px solid var(--border-color, rgba(0, 229, 255, 0.25));
          box-shadow: inset 0 0 24px rgba(0, 229, 255, 0.15);
        }
        .imageset-avatar__bracket {
          position: absolute;
          width: 12px;
          height: 12px;
          border: 2px solid var(--accent, #00e5ff);
          z-index: 4;
        }
        .imageset-avatar__bracket--tl {
          top: 4px; left: 4px;
          border-right: none; border-bottom: none;
        }
        .imageset-avatar__bracket--tr {
          top: 4px; right: 4px;
          border-left: none; border-bottom: none;
        }
        .imageset-avatar__bracket--bl {
          bottom: 4px; left: 4px;
          border-right: none; border-top: none;
        }
        .imageset-avatar__bracket--br {
          bottom: 4px; right: 4px;
          border-left: none; border-top: none;
        }
        .imageset-avatar__scan {
          position: absolute;
          inset: 0;
          background: linear-gradient(
            180deg,
            transparent 0%,
            rgba(0, 229, 255, 0.18) 50%,
            transparent 100%
          );
          background-size: 100% 8px;
          animation: imageset-scan 2.4s linear infinite;
          pointer-events: none;
          z-index: 3;
        }
        @keyframes imageset-scan {
          0%   { background-position: 0 -100%; }
          100% { background-position: 0 200%; }
        }
        .imageset-avatar__canvas {
          position: relative;
          width: 100%;
          height: 100%;
          will-change: transform;
        }
        .imageset-avatar__img,
        .imageset-avatar__video {
          position: absolute;
          inset: 0;
          width: 100%;
          height: 100%;
          object-fit: cover;
          object-position: center;
          user-select: none;
        }
        .imageset-avatar__video {
          mix-blend-mode: screen;
          opacity: 0.85;
          pointer-events: none;
        }
        .imageset-avatar__status {
          position: absolute;
          bottom: 4px;
          right: 6px;
          font-family: "Orbitron", "JetBrains Mono", monospace;
          font-size: 9px;
          letter-spacing: 0.2em;
          color: var(--accent, #00e5ff);
          opacity: 0.7;
          z-index: 5;
        }
      `}</style>
    </div>
  );
}

export default ImageSetAvatar;
